// The 42 practice categories in the LawBid app (apps/api/prisma/seed/practice_areas.seed.json),
// with their sub-specialties. Images are the app's own category art.

export type PracticeArea = {
  slug: string;
  name: string;
  image: string;
  specialties: readonly string[];
};

export const practiceAreas: readonly PracticeArea[] = [
  {
    slug: "criminal-defense",
    name: "Criminal Defense",
    image: "/images/practice/criminal-defense.webp",
    specialties: [
      "General Criminal Defense",
      "Felony",
      "Misdemeanor",
      "Drug Offenses",
      "Theft and Burglary",
      "Robbery",
      "Assault and Battery",
      "Domestic Violence Charges",
      "Sex Crimes",
      "Weapons Charges",
      "White Collar Crime",
      "Fraud and Embezzlement",
      "Cyber Crimes",
      "Homicide and Manslaughter",
      "Federal Crimes",
      "Juvenile Crimes",
      "Probation and Parole Violation",
      "Bail and Bond Hearings",
      "Expungement and Record Sealing",
      "Criminal Appeals and Post-Conviction",
      "Restraining Order Violations",
      "Public Intoxication and Disorderly Conduct",
    ],
  },
  {
    slug: "dui-and-dwi",
    name: "DUI and DWI",
    image: "/images/practice/dui-and-dwi.webp",
    specialties: [
      "First Offense DUI",
      "Repeat DUI",
      "Felony DUI",
      "Underage DUI",
      "Commercial Driver DUI",
      "Drugged Driving",
      "DMV License Suspension Hearing",
      "Ignition Interlock",
      "Refusal of Chemical Test",
    ],
  },
  {
    slug: "traffic-tickets",
    name: "Traffic Tickets",
    image: "/images/practice/traffic-tickets.webp",
    specialties: [
      "Speeding",
      "Reckless Driving",
      "Red Light and Stop Sign",
      "Driving Without License or Insurance",
      "License Suspension and Revocation",
      "Hit and Run",
      "CDL Violations",
      "Moving Violations",
      "Parking Tickets",
      "Point Reduction",
      "Traffic Court Representation",
      "Seat Belt and Cell Phone Violations",
    ],
  },
  {
    slug: "personal-injury",
    name: "Personal Injury",
    image: "/images/practice/personal-injury.webp",
    specialties: [
      "Car Accident",
      "Truck Accident",
      "Motorcycle Accident",
      "Pedestrian and Bicycle Accident",
      "Rideshare Accident",
      "Bus and Train Accident",
      "Slip and Fall",
      "Premises Liability",
      "Dog Bite",
      "Product Liability",
      "Wrongful Death",
      "Catastrophic Injury",
      "Traumatic Brain Injury",
      "Spinal Cord Injury",
      "Burn Injury",
      "Nursing Home Abuse and Neglect",
      "Assault Injury",
      "Toxic Exposure",
      "Boating Accident",
      "Construction Accident",
      "Sexual Abuse Claims",
      "Other Personal Injury",
    ],
  },
  {
    slug: "medical-malpractice",
    name: "Medical Malpractice",
    image: "/images/practice/medical-malpractice.webp",
    specialties: [
      "Surgical Error",
      "Misdiagnosis and Delayed Diagnosis",
      "Birth Injury",
      "Medication Error",
      "Anesthesia Error",
      "Hospital Negligence",
      "Dental Malpractice",
      "Nursing Negligence",
      "Wrongful Death Medical",
    ],
  },
  {
    slug: "workers-compensation",
    name: "Workers Compensation",
    image: "/images/practice/workers-compensation.webp",
    specialties: [
      "Workplace Injury",
      "Occupational Disease",
      "Denied Workers Comp Claim",
      "Return to Work Disputes",
      "Third-Party Claims",
      "Workers Comp Appeals",
      "Permanent Disability",
      "Retaliation for Filing a Claim",
    ],
  },
  {
    slug: "family-law",
    name: "Family Law",
    image: "/images/practice/family-law.webp",
    specialties: [
      "Divorce",
      "Legal Separation",
      "Child Custody",
      "Child Support",
      "Alimony and Spousal Support",
      "Property Division",
      "Prenuptial and Postnuptial Agreements",
      "Paternity",
      "Adoption",
      "Guardianship of Minors",
      "Domestic Violence Protective Orders",
      "Modification and Enforcement of Orders",
      "Grandparents Rights",
      "Name Change",
      "Annulment",
      "Surrogacy and Assisted Reproduction",
      "Relocation with Children",
      "Military Divorce",
    ],
  },
  {
    slug: "immigration",
    name: "Immigration",
    image: "/images/practice/immigration.webp",
    specialties: [
      "Family-Based Immigration",
      "Employment Visas",
      "Green Card",
      "Citizenship and Naturalization",
      "Asylum and Refugee",
      "Deportation and Removal Defense",
      "DACA",
      "Student Visas",
      "Investor Visas",
      "Waivers",
      "Temporary Protected Status",
      "U and T Visas",
      "VAWA",
      "Immigration Appeals",
      "Detention and Bond Hearings",
      "Consular Processing",
      "Visa Overstay",
    ],
  },
  {
    slug: "estate-planning-and-probate",
    name: "Estate Planning and Probate",
    image: "/images/practice/estate-planning-and-probate.webp",
    specialties: [
      "Wills",
      "Trusts",
      "Probate Administration",
      "Estate Litigation",
      "Trust Administration",
      "Power of Attorney",
      "Healthcare Directives",
      "Guardianship and Conservatorship",
      "Estate Tax Planning",
      "Beneficiary Disputes",
    ],
  },
  {
    slug: "elder-law",
    name: "Elder Law",
    image: "/images/practice/elder-law.webp",
    specialties: [
      "Medicaid Planning",
      "Long-Term Care Planning",
      "Elder Abuse",
      "Adult Guardianship",
      "Nursing Home Issues",
      "Special Needs Planning",
    ],
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    image: "/images/practice/real-estate.webp",
    specialties: [
      "Residential Purchase and Sale",
      "Commercial Real Estate",
      "Closing and Title",
      "Title Disputes and Quiet Title",
      "Foreclosure Defense",
      "Mortgage Disputes",
      "Boundary and Easement Disputes",
      "HOA Disputes",
      "Zoning and Land Use",
      "Eminent Domain",
      "Real Estate Litigation",
    ],
  },
  {
    slug: "landlord-and-tenant",
    name: "Landlord and Tenant",
    image: "/images/practice/landlord-and-tenant.webp",
    specialties: [
      "Eviction Defense",
      "Eviction for Landlords",
      "Lease Review and Disputes",
      "Security Deposit Disputes",
      "Habitability and Repairs",
      "Rent Disputes",
      "Commercial Lease Disputes",
      "Housing Discrimination",
    ],
  },
  {
    slug: "employment-and-labor",
    name: "Employment and Labor",
    image: "/images/practice/employment-and-labor.webp",
    specialties: [
      "Wrongful Termination",
      "Workplace Discrimination",
      "Sexual Harassment",
      "Wage and Hour",
      "Retaliation and Whistleblower",
      "Employment Contracts and Severance",
      "Non-Compete Agreements",
      "FMLA and Leave",
      "Unemployment Benefits",
      "Union and Labor Relations",
      "Employer-Side Representation",
      "Workplace Investigations",
    ],
  },
  {
    slug: "bankruptcy-and-debt",
    name: "Bankruptcy and Debt",
    image: "/images/practice/bankruptcy-and-debt.webp",
    specialties: [
      "Chapter 7 Bankruptcy",
      "Chapter 11 Bankruptcy",
      "Chapter 13 Bankruptcy",
      "Debt Settlement",
      "Creditor Harassment",
      "Wage Garnishment",
      "Repossession",
      "Student Loan Debt",
      "Credit Report Disputes",
      "Judgment Defense",
    ],
  },
  {
    slug: "business-and-corporate",
    name: "Business and Corporate",
    image: "/images/practice/business-and-corporate.webp",
    specialties: [
      "Business Formation",
      "Contracts",
      "Mergers and Acquisitions",
      "Partnership and Shareholder Disputes",
      "Commercial Litigation",
      "Franchise Law",
      "Corporate Governance",
      "Startups and Venture Capital",
      "Business Sale and Purchase",
      "Regulatory Compliance",
      "Business Dissolution",
      "Licensing Agreements",
    ],
  },
  {
    slug: "intellectual-property",
    name: "Intellectual Property",
    image: "/images/practice/intellectual-property.webp",
    specialties: [
      "Patents",
      "Trademarks",
      "Copyright",
      "Trade Secrets",
      "IP Litigation",
      "DMCA and Online Infringement",
      "Licensing",
    ],
  },
  {
    slug: "tax-law",
    name: "Tax Law",
    image: "/images/practice/tax-law.webp",
    specialties: [
      "IRS Audits",
      "Tax Debt Settlement",
      "Tax Planning",
      "Criminal Tax Defense",
      "Payroll Tax",
      "State and Local Tax",
      "International Tax",
      "Tax Court and Appeals",
      "Innocent Spouse Relief",
      "Back Taxes and Liens",
    ],
  },
  {
    slug: "civil-litigation",
    name: "Civil Litigation",
    image: "/images/practice/civil-litigation.webp",
    specialties: [
      "General Civil Litigation",
      "Contract Disputes",
      "Business Torts",
      "Defamation and Libel",
      "Property Damage",
      "Small Claims",
      "Class Action",
      "Mass Torts",
      "Injunctions and Restraining Orders",
      "Collections and Judgment Enforcement",
      "Civil Fraud",
      "Arbitration and Mediation Representation",
    ],
  },
  {
    slug: "consumer-protection",
    name: "Consumer Protection",
    image: "/images/practice/consumer-protection.webp",
    specialties: [
      "Consumer Fraud",
      "Lemon Law",
      "False Advertising",
      "Identity Theft",
      "Unfair Debt Collection",
      "Warranty Claims",
      "Auto Dealer Fraud",
      "Data Breach",
      "Telemarketing and Robocalls",
      "Scams and Fraud Recovery",
    ],
  },
  {
    slug: "insurance-law",
    name: "Insurance Law",
    image: "/images/practice/insurance-law.webp",
    specialties: [
      "Insurance Claim Denial",
      "Bad Faith Insurance",
      "Homeowners Insurance Claims",
      "Auto Insurance Disputes",
      "Life Insurance Claims",
      "Disability Insurance Claims",
      "Health Insurance Denial",
      "Business Insurance Claims",
      "Flood and Storm Damage Claims",
    ],
  },
  {
    slug: "social-security-disability",
    name: "Social Security Disability",
    image: "/images/practice/social-security-disability.webp",
    specialties: ["SSDI", "SSI", "Denied Disability Appeals", "Continuing Disability Review", "Disability Hearings"],
  },
  {
    slug: "veterans-and-military",
    name: "Veterans and Military",
    image: "/images/practice/veterans-and-military.webp",
    specialties: [
      "VA Disability Benefits",
      "VA Appeals",
      "Military Justice and Court-Martial",
      "Discharge Upgrades",
      "Servicemembers Civil Relief Act",
      "USERRA Employment Rights",
      "Military Family Law",
    ],
  },
  {
    slug: "civil-rights",
    name: "Civil Rights",
    image: "/images/practice/civil-rights.webp",
    specialties: [
      "Police Misconduct",
      "Section 1983 Claims",
      "Wrongful Conviction",
      "Prisoner Rights",
      "Disability Rights and ADA",
      "Voting Rights",
      "First Amendment",
      "Religious Freedom",
      "Discrimination in Public Services",
    ],
  },
  {
    slug: "education-law",
    name: "Education Law",
    image: "/images/practice/education-law.webp",
    specialties: [
      "Student Discipline",
      "Special Education and IEP",
      "Title IX",
      "University Disputes",
      "School Negligence",
      "Student Rights",
    ],
  },
  {
    slug: "health-care-law",
    name: "Health Care Law",
    image: "/images/practice/health-care-law.webp",
    specialties: [
      "Medical License Defense",
      "HIPAA and Compliance",
      "Medicare and Medicaid Billing",
      "Provider Disputes",
      "Patient Rights",
      "Medical Billing Disputes",
    ],
  },
  {
    slug: "government-and-administrative-law",
    name: "Government and Administrative Law",
    image: "/images/practice/government-and-administrative-law.webp",
    specialties: [
      "Administrative Hearings",
      "Professional License Defense",
      "Government Contracts",
      "FOIA and Public Records",
      "Permits and Licensing",
      "Public Benefits",
      "Municipal Law",
      "Agency Appeals",
    ],
  },
  {
    slug: "appeals",
    name: "Appeals",
    image: "/images/practice/appeals.webp",
    specialties: [
      "Civil Appeals",
      "Criminal Appeals",
      "Federal Appeals",
      "Writs and Extraordinary Relief",
      "Appellate Briefs",
    ],
  },
  {
    slug: "construction-law",
    name: "Construction Law",
    image: "/images/practice/construction-law.webp",
    specialties: [
      "Contractor Disputes",
      "Mechanics Liens",
      "Construction Defects",
      "Construction Contracts",
      "Surety Bonds",
    ],
  },
  {
    slug: "securities-and-financial-law",
    name: "Securities and Financial Law",
    image: "/images/practice/securities-and-financial-law.webp",
    specialties: [
      "Securities Fraud",
      "Investment Fraud and FINRA",
      "Banking and Finance",
      "Financial Regulation",
      "Cryptocurrency and Blockchain",
      "Ponzi Schemes",
    ],
  },
  {
    slug: "environmental-and-energy-law",
    name: "Environmental and Energy Law",
    image: "/images/practice/environmental-and-energy-law.webp",
    specialties: [
      "Environmental Compliance",
      "Toxic Torts",
      "Oil and Gas",
      "Renewable Energy",
      "Land Contamination",
      "Water Rights",
    ],
  },
  {
    slug: "technology-privacy-and-cyber-law",
    name: "Technology, Privacy and Cyber Law",
    image: "/images/practice/technology-privacy-and-cyber-law.webp",
    specialties: [
      "Data Privacy Compliance",
      "Cybersecurity Incidents",
      "Software and Technology Contracts",
      "Internet and E-Commerce Law",
      "Online Defamation",
      "Social Media Disputes",
    ],
  },
  {
    slug: "entertainment-media-and-sports-law",
    name: "Entertainment, Media and Sports Law",
    image: "/images/practice/entertainment-media-and-sports-law.webp",
    specialties: [
      "Entertainment Contracts",
      "Film and Music",
      "Media and Publishing",
      "Athlete Contracts",
      "Publicity and Image Rights",
    ],
  },
  {
    slug: "aviation-and-maritime-law",
    name: "Aviation and Maritime Law",
    image: "/images/practice/aviation-and-maritime-law.webp",
    specialties: [
      "Aviation Accidents",
      "Airline Passenger Rights",
      "Maritime Injury and Jones Act",
      "Admiralty",
      "Cargo Disputes",
    ],
  },
  {
    slug: "international-and-cross-border-law",
    name: "International and Cross-Border Law",
    image: "/images/practice/international-and-cross-border-law.webp",
    specialties: [
      "International Business",
      "International Family Law and Hague Convention",
      "Extradition",
      "Foreign Judgments",
      "Customs and Trade",
    ],
  },
  {
    slug: "antitrust-and-trade-regulation",
    name: "Antitrust and Trade Regulation",
    image: "/images/practice/antitrust-and-trade-regulation.webp",
    specialties: ["Antitrust", "Unfair Competition", "Price Fixing", "Trade Regulation"],
  },
  {
    slug: "nonprofit-and-religious-organizations",
    name: "Nonprofit and Religious Organizations",
    image: "/images/practice/nonprofit-and-religious-organizations.webp",
    specialties: ["Nonprofit Formation", "Tax-Exempt Status", "Nonprofit Governance", "Religious Organizations"],
  },
  {
    slug: "native-american-and-tribal-law",
    name: "Native American and Tribal Law",
    image: "/images/practice/native-american-and-tribal-law.webp",
    specialties: ["Tribal Jurisdiction", "Indian Child Welfare", "Tribal Land and Property"],
  },
  {
    slug: "animal-law",
    name: "Animal Law",
    image: "/images/practice/animal-law.webp",
    specialties: ["Animal Cruelty", "Pet Custody", "Dangerous Dog Cases", "Veterinary Malpractice"],
  },
  {
    slug: "cannabis-alcohol-and-firearms-law",
    name: "Cannabis, Alcohol and Firearms Law",
    image: "/images/practice/cannabis-alcohol-and-firearms-law.webp",
    specialties: ["Cannabis Licensing", "Alcohol Licensing", "Firearms Licensing", "Firearms Rights Restoration"],
  },
  {
    slug: "agriculture-and-gaming-law",
    name: "Agriculture and Gaming Law",
    image: "/images/practice/agriculture-and-gaming-law.webp",
    specialties: ["Agricultural Law", "Gaming and Gambling Law"],
  },
  {
    slug: "legal-malpractice",
    name: "Legal Malpractice",
    image: "/images/practice/legal-malpractice.webp",
    specialties: ["Attorney Negligence", "Attorney Fee Disputes", "Attorney Ethics Complaints"],
  },
  {
    slug: "general-practice",
    name: "General Practice",
    image: "/images/practice/general-practice.webp",
    specialties: ["General Practice", "Not Sure or Other"],
  },
];

export const practiceAreaCount = practiceAreas.length;

/** Short names for the scrolling ticker on the home page. */
export const practiceAreaNames: readonly string[] = practiceAreas.map((a) => a.name);
